// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB888vVD-rALFgSSgh8yJw7QccOfx_xHT4',
    appId: '1:1085093252774:web:00fc55a403c0192a7e2e67',
    messagingSenderId: '1085093252774',
    projectId: 'facultypay',
    authDomain: 'facultypay.firebaseapp.com',
    storageBucket: 'facultypay.firebasestorage.app',
    measurementId: 'G-GMQF5HGFQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBycG2CXCfYuLz68dXhAG5NKtZGIu0sGQo',
    appId: '1:1085093252774:android:c2446a40645270dc7e2e67',
    messagingSenderId: '1085093252774',
    projectId: 'facultypay',
    storageBucket: 'facultypay.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBwohDvngZzWrB-T2Rd9-8aeIB7Mr8V8g',
    appId: '1:1085093252774:ios:999ce622be50c5797e2e67',
    messagingSenderId: '1085093252774',
    projectId: 'facultypay',
    storageBucket: 'facultypay.firebasestorage.app',
    androidClientId: '1085093252774-nitvptcsla67ebibet6f5b8dfgpkis2f.apps.googleusercontent.com',
    iosClientId: '1085093252774-otr25aj5u6rm1qf384nov8vvt09k5dvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixedProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBwohDvngZzWrB-T2Rd9-8aeIB7Mr8V8g',
    appId: '1:1085093252774:ios:999ce622be50c5797e2e67',
    messagingSenderId: '1085093252774',
    projectId: 'facultypay',
    storageBucket: 'facultypay.firebasestorage.app',
    androidClientId: '1085093252774-nitvptcsla67ebibet6f5b8dfgpkis2f.apps.googleusercontent.com',
    iosClientId: '1085093252774-otr25aj5u6rm1qf384nov8vvt09k5dvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixedProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB888vVD-rALFgSSgh8yJw7QccOfx_xHT4',
    appId: '1:1085093252774:web:60abbdb17c1998e47e2e67',
    messagingSenderId: '1085093252774',
    projectId: 'facultypay',
    authDomain: 'facultypay.firebaseapp.com',
    storageBucket: 'facultypay.firebasestorage.app',
    measurementId: 'G-SPJM0END8J',
  );

}